function Unbal_Plot1(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 10-Sep-2015 09:24:58

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'on');

% Create plot
plot(Y1,'Parent',subplot1);

% Create ylabel
ylabel('Capital');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'on');

% Create plot
plot(Y2,'Parent',subplot2);

% Create ylabel
ylabel('Leisure');

