function PlotCompare(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 04-Apr-2014 16:28:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Steady State Linearization');
set(plot1(2),'DisplayName','Current State Linearization');
set(plot1(3),'DisplayName','Exact Solution');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.209130781499202 0.745148401826482 0.253588516746411 0.103881278538813]);

