function UnstFiscal_Plots(YMatrix1, YMatrix2)
%CREATEFIGURE(YMATRIX1, YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 05-Apr-2014 11:44:26

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.601027397260274 0.775 0.323972602739726]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Steady State Linearization');
set(plot1(2),'DisplayName','Current State Linearization');

% Create title
title('B');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.127607655502392 0.179794520547945 0.775 0.305614845492194]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot(YMatrix2,'Parent',axes2);

% Create title
title({'k',''});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.388556618819774 0.0373858447488566 0.253588516746411 0.0719178082191781]);

